//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNet_MVC_AngularJS_SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityDate
    {
        public int ID { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<double> HoursSpent { get; set; }
    }
}
