//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNet_MVC_AngularJS_SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ID { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Activity_Name { get; set; }
        public string Description { get; set; }
    }
}
